### ISSUE TITLE
发现 OpenAPI 开发文档两处错误

### ISSUE THREAD

**Issue by yureng** [gizwits-docs/gizwits-docs#109]
根据 Gizwits OpenAPI 进行开发应用，发现在线文档中错误有不少。
其中会影响到接口调用和调试的，发现以下两次：

1、获取APP Token：文档描述接口响应参数是 expire_at ，实际是 expired_at（而用户登录接口，响应参数又仍是 expire_at）；

2、验证码的获取和校验：文档描述header参数是  X-Gizwits-User-token， 实际是 X-Gizwits-Application-Token；

**Comment by smallCC** [comment]
感谢您的反馈, 我们已经更新 #115
