### ISSUE TITLE
编译不成功

### ISSUE THREAD

**Issue by laosierZhao** [gizwits-docs/gizwits-docs#37]
基于http://docs.gizwits.com/zh-cn/AppDev/AndroidSDKA2.html这个例子验证是，执行到第六步（第六步、测试是否成功         如果有下面图片中的log的话代表成功）发现如下问题，如何解决？

03/04 21:11:50: Launching app
$ adb push D:\devlopment\android\gizWifi\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.example.administrator.gizwifiapp
$ adb shell pm install -r "/data/local/tmp/com.example.administrator.gizwifiapp"
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

**Comment by littlee** [comment]
请看下最新的文档
