### ISSUE TITLE
多个产品关联一个应用这个功能怎么没有了啊？

### ISSUE THREAD

**Issue by chendong0120** [gizwits-docs/gizwits-docs#6]

**Comment by chendong0120** [comment]
这个问题真的是很着急啊！我原来一个应用都关联了三个产品了，现在要开发第4个突然就不能用了。已哭晕啊！！！

**Comment by maidongdong** [comment]
可以暂时通过旧版的开发者中心设置http://site.gizwits.com/zh-cn/developer/product
新版也即将会恢复一个应用关联多个产品的功能。

**Comment by chendong0120** [comment]
谢谢！
