### ISSUE TITLE
[网盘链接失效]Arduino Uno WiFi智能小夜灯百度

### ISSUE THREAD

**Issue by ruin1990** [gizwits-docs/gizwits-docs#76]
3.2章里的
产品制作完成
最后附上本次项目的源码下载链接如下：
链接：http://pan.baidu.com/s/1pLAnMTd 密码：c4an

对应网址：
http://docs.gizwits.com/zh-cn/deviceDev/ArduinoUNO/example.html#4-相关支持

**Comment by hohuiking** [comment]
已修复网盘链接

**Comment by littlee** [comment]
呵呵

**Comment by littlee** [comment]
解决了请 close
