### ISSUE TITLE
聚合数据的接口没看到啊

### ISSUE THREAD

**Issue by zh-h** [gizwits-docs/gizwits-docs#8]
这个 [http://api.gizwits.com/doc/#!/default/get_app_devdata_did_agg_data](Swagger) 文档里所有接口都有，新版文档中心里我和别人都找了好久，没找到[http://docs.gizwits.com/zh-cn/Cloud/OpenAPI.html](OpenAPI)

**Comment by maidongdong** [comment]
感谢您的反馈，会陆续补全
